version: 2
jobs:
  build:
    working_directory: ~/phovea
    docker:
      - image: circleci/node:12-browsers
    tags:
      - /v\d+.\d+.\d+.*/
    steps:
      - checkout
      - run:
          name: Show node and npm version
          command: |
            node -v
            npm -v
      # - run:
      #     name: NPM Force Resolutions
      #     command: npx npm-force-resolutions
      # - restore_cache:
      #     key: deps4-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm ci
      # - run:
      #     name: Remove npm dependencies installed from git repositories (avoid caching of old commits)
      #     command: |
      #       (grep -l '._resolved.: .\(git[^:]*\|bitbucket\):' ./node_modules/*/package.json || true) | xargs -r dirname | xargs -r rm -rf
      # - save_cache:
      #     key: deps4-{{ .Branch }}-{{ checksum "package.json" }}
      #     paths:
      #     - ./node_modules
      # - run:
      #     name: Install npm dependencies from git repositories (always get latest commit)
      #     command: npm install
      - run:
          name: List node_modules directory
          command: ls -la ./node_modules
      - run:
          name: Show installed npm dependencies
          command: |
            npm list phovea_core
            echo "phovea"
      - run:
          name: dist
          command: npm run dist
      - store_artifacts:
          path: dist

workflows:
  version: 2
  build-branch:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
